# Spring Boot Application Configuration
spring.application.name=cordys-crm
server.port=8081

# Import commons.properties
spring.config.import=classpath:commons.properties

# Logging configuration
logging.file.path=${LOGGING_FILE_PATH:${java.io.tmpdir}/cordys-logs}

# SpringDoc configuration
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.api-docs.groups.enabled=true
