site_name: 'Cordys CRM 在线文档'
site_url: 'https://cordys.cn/docs/'
site_description: 'Cordys CRM 在线文档'
site_author: '飞致云'
repo_name: 'Cordys CRM'
repo_url: 'https://github.com/1Panel-dev/CordysCRM'

edit_uri: https://github.com/1Panel-dev/CordysCRM-Docs
docs_dir: manual
theme:
    name: 'material'
    logo: 'img/logo-white.png'
    favicon: 'img/cordys.png'
    language: 'zh'
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    palette:
        - scheme: default
          accent: teal
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - scheme: slate
          accent: teal
          toggle:
              icon: material/weather-night
              name: Switch to light mode
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.indexes
        - navigation.top
        - search.suggest
        - search.highlight
        - search.share
        - header.autohide
        - content.tabs.link
    custom_dir: "theme"
nav:
    - 产品介绍: index.md
    - 快速入门: quick_start.md
    - 教学视频: https://www.bilibili.com/video/BV1bAHczdESW/
    - 系统架构: system_arch.md
    - 安装部署:
        - 1Panel 安装: installation/1panel_installtion.md
        - 在线安装: installation/online_installtion.md
        - Windows 安装: installation/win.md
        - 云市场安装: installation/aliyun.md
        - 离线安装: installation/offline_installtion.md        
        - 离线升级: installation/offline_upgrade.md
        - 命令行工具: installation/cli.md
        - 常见问题: installation/faq.md
    - 功能手册:
        - 组织架构管理: user_manual/org_manage.md
        - 角色与权限配置:  user_manual/role_permission.md
        - 业务表单配置: user_manual/form_config.md
        - 产品信息录入与管理: user_manual/product_entry.md
        - 销售管理与运营: user_manual/sales_manage.md
        - 企业微信集成与配置: user_manual/wecom.md
        - 移动端访问与操作:  user_manual/mobile.md
        - 接入 SQLBot 进行智能问数:  user_manual/sqlbot.md
        - 接入 DataEase 进行数据分析:  user_manual/dataease.md
        - 接入 MaxKB 实现销售智能体:  user_manual/maxkb.md
    - MCP 服务: mcp_server.md
    - 更新日志: changelog.md
    - 联系我们: contact.md
    - 商业版本: enterprise.md
    
markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: True
          linenums: False
    - toc:
          permalink: True
    - footnotes
    - attr_list
    - def_list
    - tables
    - abbr
    - md_in_html
    - pymdownx.extra
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.progressbar
    - pymdownx.tabbed:
        alternate_style: true

extra_css:
    - css/extra.css

copyright: Copyright &copy; 2014-2025 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备15023818号</a>

plugins:
    - search:
          lang:
              - en
              - ja
          separator: '[\s\-\.]+'
extra:
    version:
      provider: mike
      warning: false
    analytics:
      provider: google
      property: G-3TWT2BFLFM
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/1Panel-dev/CordysCRM
      - icon: fontawesome/solid/envelope
        link: mailto:support@fit2cloud.com
      - icon: fontawesome/solid/phone
        link: tel://400-052-0755
